import { Noto_Sans_JP } from 'next/font/google'
import { Header } from '@/components/header'
import '@/styles/globals.css'

const notoSansJp = Noto_Sans_JP({
  weight: ['400', '500', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'SasaBlog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang={'ja'}>
      <body className={notoSansJp.className}>
        <Header />
        <div className={'max-w-5xl'} m={'auto'}>
          {children}
        </div>
      </body>
    </html>
  )
}
